//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;


// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


// Important to have this attributes tag to because that is the root tag of the file.
[XmlRoot("Configuration")]
public class Configuration
{
    [XmlElement("Setting")]
    public Setting[] Setting { get; set; }
}

public class Setting
{
    public string Id { get; set; }
    public string Description { get; set; }
    public string Value { get; set; }
}
