namespace NthDimension.Compute
{
	/// <summary>
	/// The device info query symbols.
	/// </summary>
	public enum ComputeDeviceInfo
	{
		/// <summary> </summary>
		Type = 0x1000,
		/// <summary> </summary>
		VendorId = 4097,
		/// <summary> </summary>
		MaxComputeUnits = 4098,
		/// <summary> </summary>
		MaxWorkItemDimensions = 4099,
		/// <summary> </summary>
		MaxWorkGroupSize = 4100,
		/// <summary> </summary>
		MaxWorkItemSizes = 4101,
		/// <summary> </summary>
		PreferredVectorWidthChar = 4102,
		/// <summary> </summary>
		PreferredVectorWidthShort = 4103,
		/// <summary> </summary>
		PreferredVectorWidthInt = 4104,
		/// <summary> </summary>
		PreferredVectorWidthLong = 4105,
		/// <summary> </summary>
		PreferredVectorWidthFloat = 4106,
		/// <summary> </summary>
		PreferredVectorWidthDouble = 4107,
		/// <summary> </summary>
		MaxClockFrequency = 4108,
		/// <summary> </summary>
		AddressBits = 4109,
		/// <summary> </summary>
		MaxReadImageArguments = 4110,
		/// <summary> </summary>
		MaxWriteImageArguments = 4111,
		/// <summary> </summary>
		MaxMemoryAllocationSize = 4112,
		/// <summary> </summary>
		Image2DMaxWidth = 4113,
		/// <summary> </summary>
		Image2DMaxHeight = 4114,
		/// <summary> </summary>
		Image3DMaxWidth = 4115,
		/// <summary> </summary>
		Image3DMaxHeight = 4116,
		/// <summary> </summary>
		Image3DMaxDepth = 4117,
		/// <summary> </summary>
		ImageSupport = 4118,
		/// <summary> </summary>
		MaxParameterSize = 4119,
		/// <summary> </summary>
		MaxSamplers = 4120,
		/// <summary> </summary>
		MemoryBaseAddressAlignment = 4121,
		/// <summary> </summary>
		MinDataTypeAlignmentSize = 4122,
		/// <summary> </summary>
		SingleFPConfig = 4123,
		/// <summary> </summary>
		GlobalMemoryCacheType = 4124,
		/// <summary> </summary>
		GlobalMemoryCachelineSize = 4125,
		/// <summary> </summary>
		GlobalMemoryCacheSize = 4126,
		/// <summary> </summary>
		GlobalMemorySize = 4127,
		/// <summary> </summary>
		MaxConstantBufferSize = 4128,
		/// <summary> </summary>
		MaxConstantArguments = 4129,
		/// <summary> </summary>
		LocalMemoryType = 4130,
		/// <summary> </summary>
		LocalMemorySize = 4131,
		/// <summary> </summary>
		ErrorCorrectionSupport = 4132,
		/// <summary> </summary>
		ProfilingTimerResolution = 4133,
		/// <summary> </summary>
		EndianLittle = 4134,
		/// <summary> </summary>
		Available = 4135,
		/// <summary> </summary>
		CompilerAvailable = 4136,
		/// <summary> </summary>
		ExecutionCapabilities = 4137,
		/// <summary> </summary>
		CommandQueueProperties = 4138,
		/// <summary> </summary>
		Name = 4139,
		/// <summary> </summary>
		Vendor = 4140,
		/// <summary> </summary>
		DriverVersion = 4141,
		/// <summary> </summary>
		Profile = 4142,
		/// <summary> </summary>
		Version = 4143,
		/// <summary> </summary>
		Extensions = 4144,
		/// <summary> </summary>
		Platform = 4145,
		/// <summary> </summary>
		CL_DEVICE_DOUBLE_FP_CONFIG = 4146,
		/// <summary> </summary>
		CL_DEVICE_HALF_FP_CONFIG = 4147,
		/// <summary> </summary>
		PreferredVectorWidthHalf = 4148,
		/// <summary> </summary>
		HostUnifiedMemory = 4149,
		/// <summary> </summary>
		NativeVectorWidthChar = 4150,
		/// <summary> </summary>
		NativeVectorWidthShort = 4151,
		/// <summary> </summary>
		NativeVectorWidthInt = 4152,
		/// <summary> </summary>
		NativeVectorWidthLong = 4153,
		/// <summary> </summary>
		NativeVectorWidthFloat = 4154,
		/// <summary> </summary>
		NativeVectorWidthDouble = 4155,
		/// <summary> </summary>
		NativeVectorWidthHalf = 4156,
		/// <summary> </summary>
		OpenCLCVersion = 4157,
		/// <summary> </summary>
		CL_DEVICE_PARENT_DEVICE_EXT = 16468,
		/// <summary> </summary>
		CL_DEVICE_PARITION_TYPES_EXT = 16469,
		/// <summary> </summary>
		CL_DEVICE_AFFINITY_DOMAINS_EXT = 16470,
		/// <summary> </summary>
		CL_DEVICE_REFERENCE_COUNT_EXT = 16471,
		/// <summary> </summary>
		CL_DEVICE_PARTITION_STYLE_EXT = 16472
	}
}
